### ISSUE TITLE
Cashier UI

### ISSUE THREAD

**Issue by Thiritin** [eurofurence/fursuit-reg-tool#30]
![image](https://github.com/user-attachments/assets/845f86c2-20a2-41ef-99c1-50758604b869)

**Comment by Meow** [comment]
@Thiritin the frontend template is ready https://github.com/eurofurence/fursuit-reg-tool/commit/d4789038879c070f24e0a5cf13cfebb8b3f84d66

**Comment by Meow** [comment]
UI implemented and merged, closing as completed (backend remains to be written)
